### ISSUE TITLE
Adjust content width

### ISSUE THREAD

**Issue by Siihyun** [adrianbielawski/storybook-color-picker#24]
![image](https://user-images.githubusercontent.com/44644821/148149282-80bf50a8-b665-43b5-8f9b-6f5f5a7a85d2.png)

Hello. Thanks for providing a nice addon! I've been using this addon very useful.

But I have some problems now. When color name on palette is over content width, it displays with two lines like picture above.

Is there any way to pass a custom width to palette?

**Comment by adrianbielawski** [comment]
Hi Siihyun, thanks for the issue. I will resolve it ASAP.

**Comment by D3X** [comment]
@Siihyun in the meantime, it would probably make sense to group your purple/pink shades like you did with the black ones to display them in a single line :)

**Comment by Siihyun** [comment]
> Hi Siihyun, thanks for the issue. I will resolve it ASAP.

Thanks! :) Please let me know after you resolve this issue.

**Comment by Siihyun** [comment]
> @Siihyun in the meantime, it would probably make sense to group your purple/pink shades like you did with the black ones to display them in a single line :)

I agree. Actually it was defined by designer. So I'm planning to talk with him about this issue soon. Thanks for your opinion 😁

**Comment by adrianbielawski** [comment]
Hi Siihyun, Issue resolved. Also, there are few other changes so please have a look at CHANGELOG and prepare for the next major release.

**Comment by Siihyun** [comment]
Great! I'll wait until new major version released. Thank you! 😊
