### ISSUE TITLE
Support for Dark theme

### ISSUE THREAD

**Issue by wintercounter** [adrianbielawski/storybook-color-picker#289]
If I'm using Dark theme text will be white, because the dropdown doesn't change color. The global text color is white when using dark theme. Either specify a fixed text color, or add support for dark theme, but without support for themes the addon shouldn't rely on global contexts.

![image](https://user-images.githubusercontent.com/963776/201628667-d1e33ce0-d08b-4c89-bc5e-e81cdacf7a26.png)

**Comment by adrianbielawski** [comment]
Hi,

Thank you for this issue, I will add dark theme support as soon as possible.
